//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track
    {
        public int Id { get; set; }
        public byte[] Name { get; set; }
        public int Length { get; set; }
        public string Artist { get; set; }
        public Nullable<int> CDId { get; set; }
    
        public virtual CD CD { get; set; }
    }
}
